# Generated by Django 4.2.2 on 2023-06-15 18:33

import Exam_30_October_2022.car.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10)),
                ('car_model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(22)])),
                ('year', models.IntegerField(validators=[Exam_30_October_2022.car.validators.valid_car_year])),
                ('imageUrl', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(2)])),
            ],
        ),
    ]
